### ISSUE TITLE
AXI-Lite Write Procedure Deadlock

### ISSUE THREAD

**Issue by barri** [kraigher/axi_bfm#1]
The write procedure waits for the AWREADY signal to be asserted before asserting WVALID.
The skeleton implementation of the AXI-Lite interface, provided by Xilinx when generating an IP, waits on WVALID assertion before asserting AWREADY. This causes the transaction to deadlock.

The de-assertion of the valid signals between waits also cause issues with the provided skeleton implementation resulting in the procedure never finishing.

**Comment by kraigher** [comment]
Try the referenced commit above.

**Comment by barri** [comment]
Solves the issue. Thank you.
